# main
main:
    path: /calendar/{month}/{year}
    defaults: { _controller: dg.calendar.controller.main:handle, month: NULL, year: NULL }
    requirements:
        month: \d+
        year: \d+

# event
event:
    path: /calendar/event/{id}
    defaults: { _controller: dg.calendar.controller.main:event }

# create posts
create:
    path: /calendar/create
    defaults: { _controller: dg.calendar.controller.main:create }
    
# moderate
moderate:
    path: /calendar/moderate
    defaults: { _controller: dg.calendar.controller.main:moderate }