# main
main:
    path: /calendar
    defaults: { _controller: dg.calendar.controller.main:handle }
    
# view
view:
    path: /calendar/{month}/{year}
    defaults: { _controller: dg.calendar.controller.main:view }

# event
event:
    path: /calendar/event/{id}
    defaults: { _controller: dg.calendar.controller.main:event }

# create posts
create:
    path: /calendar/create
    defaults: { _controller: dg.calendar.controller.main:create }
    
# moderate
moderate:
    path: /calendar/moderate
    defaults: { _controller: dg.calendar.controller.main:moderate }